module.exports = [
  {
    type: 'input',
    name: 'name',
    message: 'Enter component name...',
  },
  {
    type: 'select',
    name: 'folder',
    message: 'Select screen folder...',
    choices: [
      'Login',
      'Home',
      'Bonuses',
      'Profile',
      'Promotions',
      'Stations',
      'CodeConfirm',
      'Onboarding',
      'Registration',
      'BonusCardCheck',
      'Cars',
      'AddCar',
      'Settings',
      'ProfileEdit',
      'NotificationSettings',
      'AboutApp',
      'LoyaltyTerms',
      'UseTerms',
      'FilterPage',
      'StationsList',
      'MapScreen',
      'Purchases',
      'Promotion',
      //ADD MORE SCREENS
    ],
  },
];
