export {colors} from './colors';
export {default as declension} from './declension';
export {fonts} from './fonts';
export {googleGeocodingKey} from './google';
export {ios, android, longScreen, darkMode, isIphoneX} from './platform';
export {languages} from './languages';
export {regions} from './regions';
export {sizes} from './sizes';
export {urls} from './urls';
export {width, height, top, bottom, hitSlop, padding} from './safeSpaces';
export {gradients} from './gradients';
export * from './strings';
export {privacyPolicySupportPhone} from './support';
export {fuel} from './fuel';
