export const urls = {
  baseDevURL: 'https://dev.marshal.myapp.com.ua/api/',
  baseProdURL: 'https://dev.marshal.myapp.com.ua/api/',

  checkPhone: 'check-phone',
  login: 'login',
  logout: 'logout',
  getProfile: 'profile/show',
  profileUpdate: 'profile/update',
  addCardOld: 'marshal-card/add-card',
  addCardNew: 'marshal-card/new-card',
  purchases: 'purchases',
  cars: 'profile/user-cars',
  addCar: 'profile/user-cars',
  deleteCar: 'profile/user-cars',
  getBrands: 'car/brands',
  getModels: 'car/models',
  getTank: 'car/tanks',
  gePromotions: 'profile/actions',
  getPetrolStations: 'azs/search-azs',
  biometricsAdd: 'biometric/add',
  biometricsLogin: 'biometric/login',
};
