require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'
rn_maps_path = '../node_modules/react-native-maps'
permissions_path = '../node_modules/react-native-permissions/ios'

platform :ios, '10.0'

target 'Marshal' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  pod 'GoogleMaps'
  pod 'react-native-google-maps', :path => rn_maps_path

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"

  target 'MarshalTests' do
    inherit! :complete
    # Pods for testing
  end

   use_flipper!({'Flipper' => '0.110.0', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3'})

  post_install do |installer|
    react_native_post_install(installer)
    # installer.pods_project.targets.each do |target|
    #    target.build_configurations.each do |config|
    #        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-DDONT_AUTOINSTALL_REANIMATED'
    #    end
    # end
  end

end
