export const assets = {
  ONBOARDING_1: require('./images/Onboarding_1.png'),
  ONBOARDING_2: require('./images/Onboarding_2.png'),
  ONBOARDING_3: require('./images/Onboarding_3.png'),
  MESSENGER: require('./images/Messenger.png'),
  TELEGRAM: require('./images/Telegram.png'),
  VIBER: require('./images/Viber.png'),
  QR_SCAN: require('./images/qr_scan.png'),
  NO_CARS: require('./images/no_cars.png'),
  NO_PURCHASES: require('./images/no_purchases.png'),
  NO_CARDS: require('./images/no_cards.png'),
  PROMOTION_BG_GREEN: require('./images/promotion_bg_green.png'),
  PROMOTION_BG_BLUE: require('./images/promotion_bg_blue.png'),
  PROMOTION_BG_RED: require('./images/promotion_bg_red.png'),
};
