export {default as SVG_Icons} from './svg/SVG_ICONs';
export {default as SVG_Img} from './svg/SVG_Img';

export const assets = {
  BONUSES_GIFT: require('./images/bonuses_gift.png'),
  BONUSES_ONBOARDING: require('./images/bonuses_onboarding.png'),
  MARKER: require('./images/marker-01.png'),
  MARKER_LOGO: require('./images/marker_logo.png'),
  MESSENGER: require('./images/Messenger.png'),
  NO_CARDS: require('./images/no_cards.png'),
  NO_CARS: require('./images/no_cars.png'),
  NO_PURCHASES: require('./images/no_purchases.png'),
  NO_INTERNET: require('./images/no_internet.png'),
  ONBOARDING_1: require('./images/Onboarding_1.png'),
  ONBOARDING_2: require('./images/Onboarding_2.png'),
  ONBOARDING_3: require('./images/Onboarding_3.png'),
  PROMOTION_BG_BLUE: require('./images/promotion_bg_blue.png'),
  PROMOTION_BG_GREEN: require('./images/promotion_bg_green.png'),
  PROMOTION_BG_RED: require('./images/promotion_bg_red.png'),
  QR_SCAN: require('./images/qr_scan.png'),
  TELEGRAM: require('./images/Telegram.png'),
  VIBER: require('./images/Viber.png'),
  WHATSAPP: require('./images/Whatsapp.png'),
  CARD_FRONT: require('./images/card/card-front.png'),
  CARD_BACK: require('./images/card/card-back.png'),
  BIO_TOUCH: require('./images/bio_touch.png'),
  BIO_FACE: require('./images/bio_face.png'),
  FACE_ID: require('./images/face_id.png'),
  TOUCH_ID: require('./images/touch_id.png'),
  TOUCH_ID_IOS: require('./images/touch_id_ios.png'),
  GOOGLE_PAY: require('./images/googlePay.png'),
  LOGO: require('./images/logo.png'),
  NO_NOTIFICATIONS: require('./images/no_notifications.png'),
  NO_SEARCH: require('./images/no_search.png'),
  BUY_FUEL_IN_PROGRESS: require('./images/in_progress.png'),
  FINGERPRINT: require('./images/fingerprint.png'),
  CARD_LOGO: require('./images/card_logo.png'),
  CARD_BACKGROUND: require('./images/card_background.png'),
};
